### PR TITLE
Add simply CI with GItHub Actions

### PR DESCRIPTION
**Pull request by zeriyoshi**
Add simple CI using GitHub Actions

Initially, we'll test PHP versions 8.0 to 8.3 as specified in the README.md.
We'll use the DockerHub official (not PHP Group) PHP prebuild container images.

This CI does not include checks using Valgrind or MemorySanitizer. If needed, please let me know, and I'll add them :)

example result:
https://github.com/zeriyoshi/php-xpass/actions/runs/10667357550

### CODE REVIEW

**Comment by remicollet** [comment]
Hi, thanks for proposal

I usually have low interest on CI, especially when using "Ubuntu"

And building libxcrypt from sources :(
I think it should exists https://packages.debian.org/source/bookworm/libxcrypt

**Comment by zeriyoshi** [comment]
OK, I'll try to create a CI for Fedora and EL compatible OS when I have time :)

**Comment by remicollet** [comment]
I have applied the "Rename test entries" comùit

**Comment by zeriyoshi** [comment]
I've added tests for Fedora and Enterprise Linux (I used Rocky, but feel free to choose your preferred distribution). These tests install PHP from the Remi Repository and run tests for php-xpass.

Please note the following:

- The `ubuntu-latest` in runs-on refers to the GitHub Actions instance type, not the OS.
- I haven't included ZTS tests for Fedora / EL, but I can add them if needed.
- The Debian tests are optional. We can remove them if they're not necessary.
- ~~Due to OpenSSL dependencies, we only test PHP 8.2 and later on EL9.~~
- Because of libxcrypt dependencies, we manually install libxcrypt on EL8.

Feel free to reach out if you have any questions or concerns :)

CI example: https://github.com/zeriyoshi/php-xpass/actions/runs/10694799040

old CI examples: 
- https://github.com/zeriyoshi/php-xpass/actions/runs/10694698121
- https://github.com/zeriyoshi/php-xpass/actions/runs/10686046969

**Comment by remicollet** [comment]
Merged (will probably remove the EL-8 case)

**Comment by remicollet** [comment]
FYI, I added test for official Fedora/EL PHP versions

**Comment by remicollet** [comment]
Everything seems OK now

Thanks a lot for your contribution
We are close to a first GA release

**Comment by remicollet** [comment]
@zeriyoshi FYI, I used your file as a template for another ext I own
=> https://github.com/remicollet/rpminfo

Thanks again

**Comment by zeriyoshi** [comment]
You're welcome! Glad I could contribute!

**Pull request closed without merging**
